version: "2"

services:
  postgres:
    image: postgres:9.6.10
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "../preprocess:/preprocess"
      - "../data:/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work

  adminer:
    image: adminer:4.6.3
    ports:
      - "8000:8080"

  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    volumes:
      - "./data/jupyter/:/home/jovyan"
      - "../preprocess:/home/jovyan/preprocess"
      - "../data:/home/jovyan/data"
    environment:
      PYTHONPATH: /home/jovyan